### PR TITLE
Docs: Updated sphinx & links clean up

### PR DESCRIPTION
**Pull request by denisSurkov**
[//]: # (Thanks for helping us out! Cache invalidation sucks, so your help is greatly appreciated!)

## Description

Solves https://github.com/noripyt/django-cachalot/issues/231

I've updated sphinx & sphinx theme. I could not see much difference, but keeping deps up-to-date is always good.

Added  `'sphinx.ext.autosectionlabel'`. This extension allows to make links like `<document-name:title inside document>`. I think it's easer to maintain links with this notation. If you don't think so, I could revert custom anchors back.

How to build docs:
```
cd docs/
pip install -r requirements.txt
make html
```

### CODE REVIEW

**Comment by Andrew-Chen-Wang** [comment]
reverting the anchors would be great. I think it's a neat add on but not for me. thanks!

**Comment by denisSurkov** [comment]
> reverting the anchors would be great.

I've reverted manual anchors back.

**Comment by denisSurkov** [comment]
@Andrew-Chen-Wang , can you help with review?

**Review by Andrew-Chen-Wang — APPROVED** [review]
sorry @denisSurkov but thanks for the reminder it lgtm!

**Comment by denisSurkov** [comment]
@Andrew-Chen-Wang , nothing has changed at https://django-cachalot.readthedocs.io/en/latest/introduction.html. 

Do you need to call some commands to refresh render?

**Comment by Andrew-Chen-Wang** [comment]
rtd hook might be failing will take a look

**Comment by denisSurkov** [comment]
@Andrew-Chen-Wang , kindly reminder to check read-the-docs webhook. 

I don't know, but this might be helpful: https://docs.readthedocs.io/en/stable/guides/setup/git-repo-manual.html

**Comment by Andrew-Chen-Wang** [comment]
Thank you for the reminder.
Screenshot 2023-08-08 at 11 43 51 AM

It turns out a configuration file is now required.

**Pull request merged**
