### PR TITLE
Add Django 4.1-4.2 and Python 3.11 support

### LINKED ISSUE #228: Support Django 4.2
Django 4.2 is out and it would be great to have it supported.

### PR DESCRIPTION
**Pull request by Andrew-Chen-Wang**
* Increment version to 4.6.0

Add Django 4.2 and Python 3.11 support 

Drops Django 2.2 and 4.0

Fixes #228

### CODE REVIEW

**Comment by Andrew-Chen-Wang** [comment]
Going to need to detect when we go into a transaction since Django added transaction BEGIN and COMMIT to the captured queries

**Comment by oriolclosa** [comment]
Came here to make a PR for it, found someone had done it already, amazing 😄🎉.

**Comment by Andrew-Chen-Wang** [comment]
@oriolclosa It is incomplete. Has a ton of errors due to the addition of BEGIN and COMMIT in sql query history.

Would appreciate it if you could help make a PR!

**Comment by creyD** [comment]
@Andrew-Chen-Wang Thanks for the quick response!

**Comment by creyD** [comment]
@Andrew-Chen-Wang When do you think this could be released?

**Comment by jacklinke** [comment]
Well, that's embarrassing 😵‍💫

Overlooked a very simple error `else else` in tests/write.py. Fixed in #235

**Comment by Hopiu** [comment]
Are there any remaining components required to fully support 4.2? @jacklinke, are you actively working on this? If not, I am happy to assist in resolving any issues with the failing tests.

**Comment by Andrew-Chen-Wang** [comment]
It seems like the only things missing is correcting the number of queries expected when catching the amount. The issue is that Django 4.2 catches transactions and logs them (BEGIN, COMMIT, etc.). I think the most simplest solution is to just update the query count.

**Comment by denizs** [comment]
I was lurking around, but I figured I might as well ask :sweat_smile: : Is there anyone actively working on getting this into a reviewable state ATM? I am not too familiar with the internals of this project, but with a couple of pointers, I might be able to bring this one home.

**Comment by Hopiu** [comment]
I completely forgot about those missing tests. I'll take a look at them, as soon as I have some time available.
@denizs if you are in a hurry, you are welcome to take over.

**Comment by Andrew-Chen-Wang** [comment]
thank you @jacklinke @Hopiu for your contributions!

**Comment by creyD** [comment]
Thanks everyone for your work! When can we expect a new release featuring these changes?

**Comment by denisSurkov** [comment]
@Andrew-Chen-Wang , sorry to bother you, but I think you might help with realeasing new version?

**Comment by Andrew-Chen-Wang** [comment]
Thank you for all the reminders, and apologies for the delay. 2.6.0 is now published. Thank you again for all the contributions everyone to getting this through!

**Pull request merged**
